### ISSUE TITLE
getting some errors

### ISSUE THREAD

**Issue by youhitgit** [undertheironbridge/transmission2qbt#1]
( Directories removed from the code to make it easier for you to read )

Hi I'm using transmission 4.0.6 on truenas scale

I downloaded https://files.pythonhosted.org/packages/15/9f/eabbc8c8a16db698d9c4bd24953763df2594b054237b89afe1ec56d3965e/bencode.py-4.0.0-py2.py3-none-any.whl and put the folders in the same directory as transmission2qbt.py

I used the command below in the truenas shell

--------------

**python /transmission2qbt.py /transmission /BT_backup**

---------------------------
It copies 2 torrent files and 2 resume files but then gives an error, see below ;

---------------------------------------------

**INFO:Successfully imported torrent .................
INFO:Successfully imported torrent .................**

**Traceback (most recent call last):**

  **File "transmission2qbt.py", line 255, in <module>
    sys.exit(main())
             ^^^^^^**

  **File "transmission2qbt.py", line 249, in main
    do_scan(args.transmission_config_dir, args.qbt_bt_backup_dir, args.predicate)**
  

  **File "transmission2qbt.py", line 200, in do_scan
    copy_if_wanted(**
  

  **File "transmission2qbt.py", line 158, in copy_if_wanted
    copy_to_target(**
  

 **File "transmission2qbt.py", line 137, in copy_to_target
    qbt_resume_data = map_resume_to_qbt(resume_data, info_hash)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^**
  
  **File "transmission2qbt.py", line 131, in map_resume_to_qbt
    qbt_resume_data[b"auto_managed"] = 0
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^**


**TypeError: 'bytes' object does not support item assignment**

------------------------------------------

Any help would be appreciated thanks.

**Comment by undertheironbridge** [comment]
hi

should be fixed in https://github.com/undertheironbridge/transmission2qbt/commit/5266c165414251a92af46f3fc737d2668ac3f292

**Comment by youhitgit** [comment]
Worked great !

Thank you very much !!!

**Comment by undertheironbridge** [comment]
glad to hear!

can you also let me know which qbittorrent and libtorrent versions you're using? you can find those in Help > About > Software Used. I'll add that to the table of supported versions.

**Comment by youhitgit** [comment]
TrueNAS Scale ElectricEel-24.10.0.2 (so the new docker versions of transmission and qBittorrent)

qBittorrent Version: 5.0.1
Libtorrent Version: 1.2.19.0
TrueNAS Scale addon Version: 1.0.33 

tranmission Version: 4.0.6
TrueNAS Scale addon Version: 1.0.9

**Comment by undertheironbridge** [comment]
thank you
